In [1]:
import numpy as np
import gym
import random

In [2]:
policy = np.zeros([9, 6])
policy = [[-1, 1, -1, -1, -3, 10], 
     [1, 1, -1, 1, 5, -2], 
     [1, -1, -1, -1, 5, -2], 
     [-1, 1, -1, -1, 5, -2], 
     [1, 1, 1, 1, 5, -2], 
     [1, -1, -1, -1, 5, -2], 
     [-1, 1, -1, -1, 5, -2], 
     [1, 1, 1, -1, 5, -2], 
     [1, -1, -1, -1, 5, -2]]

In [3]:
class OfficeEnv(gym.Env):

    def __init__(self):
       
        self.action_space = 6
        self.state_space = 9
        self.observation_space = 72
        reward = 0
        state = random.randint(0,self.state_space-1)

    def step(self, action):

        
        state = random.randint(0,self.state_space-1)
        reward = policy[state][action]
            
        done = True

        info = {}

        return state, reward, done, info

    def reset(self):
        state = random.randint(0,env.state_space-1)
        reward = 0
        return state

In [4]:
env = OfficeEnv()


In [5]:
q_table = np.zeros([9, 6])
print(q_table)



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [6]:
num_of_episodes = 100
max_number_of_steps_per_episode = 10 

alpha = 0.1
gamma = 0.99

rate_of_exploration = 1

In [7]:
rewards_all_episodes = []
import random
# CanBot's Q-Learning algorithm
for i in range(num_of_episodes):
    state = env.reset()
    
    done = False
    rewards = list()
    penalties = 0
    
    for step in range(max_number_of_steps_per_episode):
        
        
        if random.uniform(0,1) > rate_of_exploration: 
            action = np.argmax(policy[:, state])
        else:
            action = random.randint(0,env.action_space-1)
            #print("Action: ", action)
            #print("State: ", state)
        new_state, reward, done, info = env.step(action)
        if reward == 10:
          done = True
        q_table[state, action] = (1 - alpha) * q_table[state, action] + \
            alpha * (reward + gamma * np.max(q_table[new_state,:]))
            
        state = new_state
        rewards.append(reward) 
        
        if done == True: 
            #print("Reward for episode: ", i, ":", rewards)
            break
    rewards_all_episodes.append(sum(rewards)/len(rewards))    
    
print("Average rewards foe 100 episodes: ", rewards_all_episodes)    
print("Q-table")
print(q_table)

Average rewards foe 100 episodes:  [5.0, 5.0, -2.0, -3.0, -2.0, -2.0, -1.0, -1.0, 1.0, 5.0, 1.0, -1.0, -1.0, 1.0, 1.0, 5.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -2.0, 1.0, 1.0, -1.0, -2.0, -1.0, 1.0, -1.0, 1.0, -1.0, 1.0, -1.0, 5.0, 5.0, -2.0, -2.0, -1.0, 1.0, 5.0, -1.0, 5.0, -1.0, -1.0, -1.0, 5.0, -1.0, 1.0, 1.0, 1.0, -1.0, 5.0, -1.0, 1.0, 5.0, 1.0, -1.0, -2.0, 5.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 5.0, 5.0, -2.0, -2.0, 5.0, -2.0, -1.0, 5.0, 1.0, 1.0, -2.0, -1.0, 1.0, 5.0, -1.0, 1.0, 5.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 5.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -2.0]
Q-table
[[ 0.00000000e+00  4.06956210e-01  1.00000000e-01  3.65373681e-01
   1.36656137e+00 -1.49034751e-01]
 [-1.39561546e-03  3.77348331e-01  1.14800500e-01  3.63656343e-03
   1.53052755e+00 -5.32313124e-01]
 [ 1.94872880e-01  4.33989639e-01  2.00121242e-01  8.55152495e-02
   9.74881820e-01 -3.25599500e-01]
 [ 6.34386154e-02  0.00000000e+00  1.48154259e-01  2.61659581e-01
   1.38591739e+00 -1.49034751e-01]
 [ 

In [13]:
!jupyter nbconvert --to PDF "220079842_Office_env.ipynb"

[NbConvertApp] Converting notebook 220079842_Office_env.ipynb to PDF
[NbConvertApp] Writing 61758 bytes to ./notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: [u'xelatex', u'./notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'./notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 41077 bytes to 220079842_Office_env.pdf
